In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import warnings
warnings.filterwarnings('ignore')

In [ ]:
import os
import pandas as pd

# Define the directory containing the CSV files
directory = '/usr/realestate data'

# Initialize an empty DataFrame to hold the merged data
merged_df = pd.DataFrame()

# Loop through all files in the directory
for filename in os.listdir(directory):
    if filename.endswith('.csv'):
        file_path = os.path.join(directory, filename)
        df = pd.read_csv(file_path)
        merged_df = pd.concat([merged_df, df], ignore_index=True)

# Save the merged DataFrame to a new CSV file
merged_df.to_csv('merged_data.csv', index=False)

print("Data merged successfully. Saved to 'merged_data.csv'")


FileNotFoundError: [Errno 2] No such file or directory: '/usr/realestate data'

In [ ]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv('merged_data.csv')
df

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df.isnull().sum()

In [ ]:
df.drop(columns=['property_url','mls','mls_id','text','primary_photo','alt_photos','broker_phone','latitude','longitude'], inplace=True)

In [ ]:
df

In [ ]:
df.info()

In [ ]:
df.isnull().sum()

In [ ]:
# prompt: remove duplicates

df.drop_duplicates(inplace=True)
df


In [ ]:
df.duplicated().sum()

In [ ]:
# Creating a instance of label Encoder.
le = LabelEncoder()

# Using .fit_transform function to fit label
# encoder and return encoded label
label = le.fit_transform(df['status'])
label = le.fit_transform(df['style'])
label = le.fit_transform(df['full_street_line'])
label = le.fit_transform(df['street'])
label = le.fit_transform(df['unit'])
label = le.fit_transform(df['city'])
label = le.fit_transform(df['state'])
label = le.fit_transform(df['zip_code'])
label = le.fit_transform(df['beds'])
label = le.fit_transform(df['full_baths'])
label = le.fit_transform(df['half_baths'])
label = le.fit_transform(df['sqft'])
label = le.fit_transform(df['year_built'])
label = le.fit_transform(df['days_on_mls'])
label = le.fit_transform(df['list_price'])
label = le.fit_transform(df['list_date'])
label = le.fit_transform(df['sold_price'])
label = le.fit_transform(df['last_sold_date'])
label = le.fit_transform(df['assessed_value'])
label = le.fit_transform(df['estimated_value'])
label = le.fit_transform(df['lot_sqft'])
label = le.fit_transform(df['price_per_sqft'])
label = le.fit_transform(df['neighborhoods'])
label = le.fit_transform(df['county'])
label = le.fit_transform(df['fips_code'])
label = le.fit_transform(df['stories'])
label = le.fit_transform(df['hoa_fee'])
label = le.fit_transform(df['parking_garage'])
label = le.fit_transform(df['agent'])
label = le.fit_transform(df['agent_phones'])
label = le.fit_transform(df['agent_email'])
label = le.fit_transform(df['broker'])
label = le.fit_transform(df['broker_website'])
label = le.fit_transform(df['nearby_schools'])

# printing label
label


In [ ]:
df.drop("status", axis=1, inplace=True)
#df.drop("style", axis=1, inplace=True)
df.drop("full_street_line", axis=1, inplace=True)
df.drop("unit", axis=1, inplace=True)
df.drop("city", axis=1, inplace=True)
df.drop("state", axis=1, inplace=True)
df.drop("zip_code", axis=1, inplace=True)
df.drop("beds", axis=1, inplace=True)
df.drop("full_baths", axis=1, inplace=True)
df.drop("half_baths", axis=1, inplace=True)
df.drop("sqft", axis=1, inplace=True)
df.drop("year_built", axis=1, inplace=True)
df.drop("days_on_mls", axis=1, inplace=True)
df.drop("list_price", axis=1, inplace=True)
df.drop("list_date", axis=1, inplace=True)
df.drop("sold_price", axis=1, inplace=True)
df.drop("last_sold_date", axis=1, inplace=True)
df.drop("assessed_value", axis=1, inplace=True)
df.drop("estimated_value", axis=1, inplace=True)
df.drop("lot_sqft", axis=1, inplace=True)
df.drop("price_per_sqft", axis=1, inplace=True)
df.drop("neighborhoods", axis=1, inplace=True)
df.drop("county", axis=1, inplace=True)
df.drop("fips_code", axis=1, inplace=True)
df.drop("stories", axis=1, inplace=True)
df.drop("hoa_fee", axis=1, inplace=True)
df.drop("parking_garage", axis=1, inplace=True)
df.drop("agent", axis=1, inplace=True)
df.drop("agent_email", axis=1, inplace=True)
df.drop("agent_phones", axis=1, inplace=True)
df.drop("broker", axis=1, inplace=True)
df.drop("broker_website", axis=1, inplace=True)
df.drop("nearby_schools", axis=1, inplace=True)





In [ ]:
#Appending the array to our dataFrame
# with column name 'Purchased'
df["status"] = label
df["style"] = label
df["full_street_line"] = label
df["street"] = label
df["unit"] = label
df["city"] = label
df["state"] = label
df["zip_code"] = label
df["beds"] = label
df["full_baths"] = label
df["half_baths"] = label
df["sqft"] = label
df["year_built"] = label
df["days_on_mls"] = label
df["list_price"] = label
df["list_date"] = label
df["sold_price"] = label
df["last_sold_price"] = label
df["assessed_value"] = label
df["estimated_value"] = label
df["loft_sqft"] = label
df["price_per_sqft"] = label
df["neighborhoods"] = label
df["county"] = label
df["fips_code"] = label
df["stories"] = label
df["hoa_fee"] = label
df["parking_garage"] = label
df["agent"] = label
df["agent_email"] = label
df["agent_phones"] = label
df["broker"] = label
df["broker_website"] = label
df["nearby_schools"] = label

In [ ]:
df.info()

In [ ]:
# Assuming 'df' is your DataFrame
plt.figure(figsize=(15, 10))

# Using Seaborn to create a heatmap
sns.heatmap(df.corr(), annot=True, fmt='.2f', cmap='Pastel2', linewidths=2)

plt.title('Correlation Heatmap')
plt.show()

In [ ]:
# Set Seaborn style
sns.set_style("darkgrid")

# Identify numerical columns
numerical_columns = df.select_dtypes(include=["int64"]).columns

# Plot distribution of each numerical feature
plt.figure(figsize=(14, len(numerical_columns) * 3))
for idx, feature in enumerate(numerical_columns, 1):
    plt.subplot(len(numerical_columns), 2, idx)
    sns.histplot(df[feature], kde=True)
    plt.title(f"{feature} | Skewness: {round(df[feature].skew(), 2)}")

# Adjust layout and show plots
plt.tight_layout()
plt.show()

In [ ]:
# Assuming 'df' is your DataFrame
plt.figure(figsize=(10, 8))

# Using Seaborn to create a swarm plot
sns.swarmplot(x="status", y="street", data=df, palette='viridis')

plt.title('Swarm Plot for syle and street')
plt.xlabel('status')
plt.ylabel('street')
plt.show()

In [ ]:

# plotting the line chart
fig = px.line(df, x="nearby", y="parking_garage")

# showing the plot
fig.show()

Implementing machine learning algorithms:

In [50]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [51]:
X_train

array([[23, 23, '23', ..., 23, 23, 23],
       [62, 62, '62', ..., 62, 62, 62],
       [30, 30, '30', ..., 30, 30, 30],
       ...,
       [13, 13, '13', ..., 13, 13, 13],
       [2, 2, '2', ..., 2, 2, 2],
       [62, 62, '62', ..., 62, 62, 62]], dtype=object)

In [43]:
X_test

array([[32, 32, '32', ..., 32, 32, 32],
       [58, 58, '58', ..., 58, 58, 58],
       [22, 22, '22', ..., 22, 22, 22],
       ...,
       [10, 10, '10', ..., 10, 10, 10],
       [38, 38, '38', ..., 38, 38, 38],
       [32, 32, '32', ..., 32, 32, 32]], dtype=object)

In [44]:
y_train

array([23, 62, 30, ..., 13,  2, 62])

In [45]:
y_test

array([32, 58, 22, 22, 57, 49,  4,  7, 30, 22, 13, 55, 23, 58, 32, 32, 39,
       22, 45, 23, 32, 32, 38, 55, 32, 57, 55, 14, 35, 26, 21,  2, 22,  7,
       62, 55, 44, 30, 55, 32, 45, 35, 40, 45,  7, 32, 57, 32, 29, 22,  7,
        7, 37, 32, 23, 16, 57, 57, 32,  3, 26, 15, 32, 22, 49, 40, 55,  4,
       35,  4, 37, 58, 33, 23, 38, 55, 22,  7, 20, 55, 32, 36, 15, 13, 38,
       26, 29,  7, 13, 58, 18, 20, 13, 50, 27, 58, 34, 35, 32, 33, 13,  7,
       58, 26, 39, 32, 21, 35, 32, 57, 49, 34, 23,  9, 35, 13, 17, 32, 32,
       32, 50, 38, 55, 23, 49, 32,  3, 60, 23, 15, 26, 55, 22, 57, 23, 49,
        4, 52, 44, 58, 49, 23, 40, 14, 29, 62, 55, 35, 39, 30, 20, 29, 14,
       17, 13, 40, 38, 53, 40, 33, 15, 15,  0, 30, 23, 14, 32, 55, 34, 30,
       15, 17, 38, 35, 29,  4, 45, 11, 14,  7, 54,  7, 38, 62, 62, 30, 34,
       44, 58, 53, 61, 34, 35, 40, 23, 17, 32, 29, 34, 40, 35, 39, 32, 55,
       11,  1, 16, 20, 11, 26,  4,  7, 29, 32, 35, 11, 44, 26, 35, 11,  4,
       32, 13, 15, 34, 22

Random Forest

In [54]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
rf = RandomForestClassifier(n_estimators=100, random_state=42,max_depth = None)
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [63]:
rf_preds = rf.predict(X)
print("Classification Report")
print("Accuracy : {}".format(accuracy_score(y, rf_preds)))
print("Precision : {}".format(precision_score(y, rf_preds, average = 'macro')))
print("Recall : {}".format(recall_score(y, rf_preds,average = 'macro')))
print("F1 Score : {}".format(f1_score(y, rf_preds,average = 'macro')))

Classification Report
Accuracy : 0.9996067636649626
Precision : 0.9836860670194003
Recall : 0.9841269841269841
F1 Score : 0.9839034205231388


In [70]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=15)
knn.fit(X_train, y_train)
knn_preds = knn.predict(X)

In [71]:
print("Classification Report")
print("Accuracy : {}".format(accuracy_score(y, knn_preds)))
print("Precision : {}".format(precision_score(y, knn_preds, average = 'macro')))
print("Recall : {}".format(recall_score(y, knn_preds,average = 'macro')))
print("F1 Score : {}".format(f1_score(y, knn_preds,average = 'macro')))

Classification Report
Accuracy : 0.9720802202123476
Precision : 0.6634698295355259
Recall : 0.6825396825396826
F1 Score : 0.6723321131138914


In [72]:
pip install tensorflow_data_validation

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.0/19.0 MB 14.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 37.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.9/35.9 MB 12.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.9/99.9 kB 11.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.5/22.5 MB 9.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.5/14.5 MB 57.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.7/89.7 kB 9.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 145.0/145.0 kB 14.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.0/152.0 kB 14.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 59.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.5/43.5 kB 4.9 MB/s